### ISSUE TITLE
Include Rule Identifiers and Rule Description in Atomic Rule List

### ISSUE THREAD

**Issue by moekraft** [w3c/wcag-act#262] opened 2018-09-17 13:39 UTC
Suggest including that Rule Identifiers and Rule Descriptions are required in the Composite rules' Atomic Rule List under section 9.

From Kathy Eng, 9/13/18, WCAG ACT TF meeting. See PR #247

**Comment by maryjom** [comment] 2018-09-18 21:28
This is a duplicate of Issue #261

**Closed by maryjom** 2018-09-18 21:28 UTC
